<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{

    public function findForCategory(Category $category)
    {
        return $this->findBy('category_id', $category->getId());
    }

    public function findForUser(User $user)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT t 
             FROM AppBundle:Task t
             JOIN AppBundle:Category c
             WHERE c.user = :user')
            ->setParameter('user', $user)
            ->getResult();
    }

}
